version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - mongodb_data:/data/db

  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=$

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongodb_data:
